### ISSUE TITLE
Kick all players on the server when someone uses chat

### ISSUE THREAD

**Issue by pdenardi** [KaspianDev/AntiPopup#7]
![imagen_2022-08-06_184354865](https://user-images.githubusercontent.com/91810694/183266973-3f2760a3-704e-49bb-8fec-6a99bb44a8c9.png)

I used Purpur 1.19.2-build 1752

**Comment by KaspianDev** [comment]
@pdenardi does this happen on 1.19.1?

**Comment by pdenardi** [comment]
@KaspianDev No, in 1.19.1 it works perfectly, this happened when updating to 1.19.2

**Comment by pdenardi** [comment]
`[18:32:34 INFO]: UUID of player PattoDonaldTv is 9b0e5d92-531d-33eb-a911-75294472b654
[18:32:34 INFO]: PattoDonaldTv joined the game
[18:32:34 INFO]: PattoDonaldTv[/127.0.0.1:58224] logged in with entity id 335 at ([Survival]25.428794301257852, 75.0, -6.209659093372887)
[18:32:38 INFO]: [Not Secure] <PattoDonaldTv> a
[18:32:38 INFO]: PattoDonaldTv lost connection: Internal Exception: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.d()'
[18:32:38 INFO]: PattoDonaldTv left the game
[18:32:40 INFO]: UUID of player PattoDonaldTv is 9b0e5d92-531d-33eb-a911-75294472b654
[18:32:40 INFO]: PattoDonaldTv joined the game
[18:32:40 INFO]: PattoDonaldTv[/127.0.0.1:58230] logged in with entity id 346 at ([Survival]25.428794301257852, 75.0, -6.209659093372887)
[18:32:46 INFO]: PattoDonaldTv issued server command: /plugman load AntiPopup (1)
[18:32:46 INFO]: [AntiPopup] Loading 1 libraries... please wait
[18:32:46 INFO]: [AntiPopup] Loaded library E:\Documentos\ComunidadDestiny\MC Survival\libraries\dev\dejvokep\boosted-yaml-spigot\1.3\boosted-yaml-spigot-1.3.jar
[18:32:46 INFO]: [AntiPopup] Loaded PacketEvents
[18:32:46 INFO]: [AntiPopup] Enabling AntiPopup v3.1
[18:32:46 INFO]: [AntiPopup] Config enabled.
[18:32:46 INFO]: [AntiPopup] Initiated PacketEvents
[18:32:46 INFO]: [AntiPopup] Command registered.
[18:32:51 INFO]: PattoDonaldTv issued server command: /plugman unload NoEncryption
[18:32:51 INFO]: [NoEncryption] Disabling NoEncryption v2.0
[18:32:52 INFO]: [Not Secure] <PattoDonaldTv> a
[18:32:52 INFO]: PattoDonaldTv lost connection: Internal Exception: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.d()'
[18:32:52 INFO]: PattoDonaldTv left the game
[18:32:55 INFO]: UUID of player PattoDonaldTv is 9b0e5d92-531d-33eb-a911-75294472b654
[18:32:55 INFO]: PattoDonaldTv joined the game
[18:32:55 INFO]: PattoDonaldTv[/127.0.0.1:58239] logged in with entity id 365 at ([Survival]25.066086345667507, 75.0, -5.434050723903636)
[18:33:00 INFO]: PattoDonaldTv issued server command: /pl
[18:33:12 INFO]: PattoDonaldTv issued server command: /plugman unload AntiPopup
[18:33:12 INFO]: [AntiPopup] Disabling AntiPopup v3.1
[18:33:12 INFO]: [AntiPopup] Disabled PacketEvents
[18:33:12 INFO]: [Not Secure] <PattoDonaldTv> a
[18:33:31 INFO]: PattoDonaldTv lost connection: Disconnected
[18:33:31 INFO]: PattoDonaldTv left the game`

I tried on a new server in the same version of purpur and the same thing happens.

**Comment by pdenardi** [comment]
![imagen_2022-08-06_185050098](https://user-images.githubusercontent.com/91810694/183267154-491fa535-9544-48ae-b5e6-5f81a22dec2c.png)

I tried on a new server in the same version of purpur and the same thing happens.

**Comment by KaspianDev** [comment]
Please try with paper

**Comment by pdenardi** [comment]
![imagen_2022-08-06_190411931](https://user-images.githubusercontent.com/91810694/183267428-2adcc064-7010-4448-9b0c-58c15d7542fa.png)

Same error

**Comment by KaspianDev** [comment]
Alright since rn 1.19.2 is not supported, I'll let you know tomorrow when it's fixed.

**Comment by pdenardi** [comment]
Thanks, i wait for the update, and I give you a feedback

**Comment by KaspianDev** [comment]
@pdenardi I tried latest essentials, latest paper and don't seem to have the issue.

**Comment by KaspianDev** [comment]
I also wanna add that you should not use antipopup with other similar plugins, and never ever use plugman with plugins that touch packets.

Delete noencryption and restart your server please.

**Comment by KaspianDev** [comment]
Reopen once you read message above.

**Comment by pdenardi** [comment]
> I also wanna add that you should not use antipopup with other similar plugins, and never ever use plugman with plugins that touch packets.
> 
> Delete noencryption and restart your server please.

Apparently the issue was presented with "NoEncryption". I removed it completely and it works fine, thank you very much for the help.

**Comment by KaspianDev** [comment]
Glad I helped
